# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Dockerize ThesisCapstone

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dockerize-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Dockerize
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ${{ secrets.DOCKER_REPOSITORY_NAME }}:latest .
          docker push ${{ secrets.DOCKER_REPOSITORY_NAME }}:latest

      - name: Deploy
        run: |
          ssh ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }} "docker pull ${{ secrets.DOCKER_REPOSITORY_NAME }}:latest"
